# Importes

In [1]:
import pandas as pd

from loaders import Loaders
from utils import Utils

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)

loaders = Loaders()
utils = Utils()

# Rutas

In [2]:
from pathlib import Path

BASE_DIR = Path.cwd()
INPUT_DIR = BASE_DIR / "input_SIDCAR"

RUTA_DOCUMENTOS = INPUT_DIR / "DocumentosElaborados.xls"
RUTA_PRERADICADOS = INPUT_DIR / "preradicados.xlsx"
RUTA_RADICADOS = INPUT_DIR / "Radicados.xlsx"

NOMBRES_OBJETIVO = [
    "FRANCY LILIANA DAZA SANCHEZ",
    "MARIA FERNANDA ARIAS OYUELA",
    "ISABEL CRISTINA ANGARITA PERPIÑAN",
    "GINA ALEXANDRA ROBERTO TORRES",
    "ALVARO ANDRES JIMENEZ VANEGAS",
]

print("BASE_DIR:", BASE_DIR)
print("INPUT_DIR:", INPUT_DIR)
print("RUTA_DOCUMENTOS:", RUTA_DOCUMENTOS)
print("RUTA_PRERADICADOS:", RUTA_PRERADICADOS)
print("RUTA_RADICADOS:", RUTA_RADICADOS)

print("\nValidación de existencia:")
print("DocumentosElaborados existe:", RUTA_DOCUMENTOS.exists())
print("preradicados existe:", RUTA_PRERADICADOS.exists())
print("Radicados existe:", RUTA_RADICADOS.exists())

BASE_DIR: c:\Users\JULIANCHO ROBLES\Desktop\PROYECTOS GITHUB\oficios_notificaciones
INPUT_DIR: c:\Users\JULIANCHO ROBLES\Desktop\PROYECTOS GITHUB\oficios_notificaciones\input_SIDCAR
RUTA_DOCUMENTOS: c:\Users\JULIANCHO ROBLES\Desktop\PROYECTOS GITHUB\oficios_notificaciones\input_SIDCAR\DocumentosElaborados.xls
RUTA_PRERADICADOS: c:\Users\JULIANCHO ROBLES\Desktop\PROYECTOS GITHUB\oficios_notificaciones\input_SIDCAR\preradicados.xlsx
RUTA_RADICADOS: c:\Users\JULIANCHO ROBLES\Desktop\PROYECTOS GITHUB\oficios_notificaciones\input_SIDCAR\Radicados.xlsx

Validación de existencia:
DocumentosElaborados existe: True
preradicados existe: True
Radicados existe: True

In [3]:
import os
from pathlib import Path

print("Directorio actual de ejecución:")
print(os.getcwd())

print("\nContenido de la carpeta actual:")
for x in os.listdir():
    print("-", x)

ruta_input = Path("input")
print("\n¿Existe carpeta input?:", ruta_input.exists())

if ruta_input.exists():
    print("\nArchivos dentro de input:")
    for x in ruta_input.iterdir():
        print("-", x.name)

Directorio actual de ejecución:
c:\Users\JULIANCHO ROBLES\Desktop\PROYECTOS GITHUB\oficios_notificaciones

Contenido de la carpeta actual:
- .git
- .gitignore
- constructor.ipynb
- description.txt
- input
- input_SIDCAR
- loaders.py
- output_abogados
- output_SIDCAR
- plantillas
- seguimiento_proy.ipynb
- sidcar.ipynb
- utils.py
- venv
- __pycache__

¿Existe carpeta input?: True

Archivos dentro de input:
- Basenotificar.xlsx

# carga

In [4]:
df_documentos = utils.cargar_excel_con_encabezado_doble(RUTA_DOCUMENTOS)
df_preradicados = utils.cargar_excel_con_encabezado_doble(RUTA_PRERADICADOS)
df_radicados = utils.cargar_excel_con_encabezado_doble(RUTA_RADICADOS)

print("DocumentosElaborados:", df_documentos.shape)
print("Preradicados:", df_preradicados.shape)
print("Radicados:", df_radicados.shape)

display(df_documentos.head(3))
display(df_preradicados.head(3))
display(df_radicados.head(3))

DocumentosElaborados: (1557, 19)
Preradicados: (1888, 10)
Radicados: (2327, 25)

,Funcionario,Expediente,Creación,Proceso,Provincial,Usuario,ACTIVIDAD ASIGNADA Etapa,Actividad,Inicio,Fin,Observaciones,TIEMPO FUNCIONARIO EN LA ACTIVIDAD Inicio,Fin_1,Días,ULTIMO DOCUMENTO ELABORADO Tipo,Descripción,Fecha,Número,Firmado por
0,ADOLFO LEÓN IBAÑEZ ELAM,93620,2022-07-06 16:02:15.080000,Afectación recurso Agua,Ubate,RIBELL SAS.,Etapa Decisoria,Acto administrativo que decide de fondo,2025-09-05 16:46:34,2026-02-04 00:00:00,Se remite proyecto con decisión de fondo para ...,2026-02-11 14:38:46.020000,2026-02-04 00:00:00,-7,Memorando,Memorando,2026-02-17 14:07:01.970000,20263018818,Emma Constanza Zuñiga Galvis(Dirección Jurídic...
1,ADOLFO LEÓN IBAÑEZ ELAM,93620,2022-07-06 16:02:15.080000,Afectación recurso Agua,Ubate,RIBELL SAS.,Etapa Decisoria,Acto administrativo que decide de fondo,2025-09-05 16:46:34,2026-02-04 00:00:00,Se atienden las observaciones incorporadas en ...,2026-02-18 12:59:02.640000,2026-02-04 00:00:00,-14,Memorando,Memorando,2026-02-17 14:07:01.970000,20263018818,Emma Constanza Zuñiga Galvis(Dirección Jurídic...
2,ADOLFO LEÓN IBAÑEZ ELAM,91035,2022-02-03 10:44:17.330000,Afectación recurso Flora,Alto Magdalena,"JOSE GABINO BLANCO BARRERA, JOSE INDALECIO MES...",Etapa de Conocimiento,Cesación de procedimiento,2026-01-29 07:05:25,NaN,"Buen día, se remite para revisión (Reparto ene...",2026-02-12 13:52:08.877000,2026-02-23 09:53:46.337000,11,Oficio,Notificación personal medio electrónico,2026-03-17 12:24:38.587000,20262020582,Emma Constanza Zuñiga Galvis(Dirección Jurídic...

,Número,Tipo Documento,Estado,Año,Información de Creación Fecha,Login,Usuario,Oficina,Asunto,Respuesta A:
0,3669770,Oficio,En Borrador,2026,2026-01-05 14:25:43.290000,nrosas,Nancy Yaneth Rosas,Dirección Regional Ubaté,Notificación por Aviso Resolución DJA No. 0096...,NaN
1,3670114,Memorando,En Borrador,2026,2026-01-05 17:11:35.850000,nrosas,Nancy Yaneth Rosas,Dirección Regional Ubaté,Solicitud dar prioridad a trámites asignados.,NaN
2,3670867,Oficio,En Borrador,2026,2026-01-06 14:26:52.433000,marevalo,Miryam Cecilia Arevalo,Dirección Regional Almeidas y Guatavita,Notificación por Aviso Auto DRAG No. 00474 de ...,NaN

,No. Doc:,Fecha Correo,# Radicado,Tipo,F Radicado,Asunto,Título,Elaboró,Revisó,Radicó,Of Radica,Estado,Medio,Tramite,Destinatarios,Remitente,Responsable,Pre-Radicado,Tipo Asunto,RegistroPor:,Ver,columna,Info SAE Expediente,Proceso,Estado Términos
0,NaN,2026-01-02 07:44:28.317000,20263000014,Memorando,2026-01-02 07:44:28.300000,observaciones al proyecto de acto administrati...,N.A,Jhoanna Alexandra Montoya Muñoz,NaN,Emma Constanza Zuñiga Galvis,DJA,Finalizado,Digital,Memorando Interno,Dirección Regional Tequendama,Dirección Jurídica Ambiental (Emma Constanza Z...,Argelio David Vargas Fragoz[Dirección Regional...,NaN,Devolucion de Acto Administrativo,ezunigag,NaN,NaN,NaN,NaN,NaN
1,NaN,2026-01-02 09:22:35.480000,20263000020,Memorando,2026-01-02 09:22:35.413000,Respuesta al radicado 06253001741: Respuesta a...,N.A,Juan Jacobo Finkielsztein Perez,NaN,Emma Constanza Zuñiga Galvis,DJA,Finalizado,Digital,Memorando Interno,Dirección Regional Gualivá,Dirección Jurídica Ambiental (Emma Constanza Z...,Aura Daniela Leon Perez[Dirección Regional Gua...,NaN,NaN,ezunigag,NaN,NaN,NaN,NaN,NaN
2,NaN,2026-01-02 09:55:54.050000,20263000021,Memorando,2026-01-02 09:55:54.013000,Respuesta al radicado 20253123863: Reporte Pub...,N.A,Barbara Maria Ospina Acevedo,Juan Jacobo Finkielsztein Perez / DJA,Emma Constanza Zuñiga Galvis,DJA,Finalizado,Digital,Memorando Interno,Secretaría General,Dirección Jurídica Ambiental (Emma Constanza Z...,Yadid Jimena Ariza Diaz[Secretaría General],NaN,Respuesta al memorando,ezunigag,NaN,NaN,NaN,NaN,NaN

# Cruce final

In [5]:
df_seguimiento = utils.construir_reporte_seguimiento_sae_sidcar(
    df_documentos_elaborados=df_documentos,
    df_preradicados=df_preradicados,
    df_radicados=df_radicados,
    nombres_objetivo=NOMBRES_OBJETIVO,
)

df_resumen = utils.construir_resumen_seguimiento_sae_sidcar(df_seguimiento)

display(df_seguimiento.head(20))
display(df_resumen)

,expediente,nombre_persona,funcionario_sae,etapa_sae,actividad_sae,ultimo_documento_tipo_sae,ultimo_documento_descripcion_sae,fecha_ultimo_documento_sae,numero_ultimo_documento_sae,firmado_por_sae,tiene_preradicado,numero_preradicado,tipo_documento_preradicado,estado_preradicado,fecha_preradicado,asunto_preradicado,tiene_radicado,numero_radicado,tipo_documento_radicado,estado_radicado,fecha_radicado,asunto_radicado,preradicado_relacionado,estado_pelota_caliente,responsable_pelota_caliente
0,102134,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Auto,Requerimiento y realiza cobro por seguimiento ...,2026-02-18 09:04:00.320,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
1,33512,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Resolución,Declara la pérdida de fuerza ejecutoria de una...,2026-02-22 22:22:43.390,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
2,57966,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Auto,Anuncia de caducidad y realiza cobro por Segui...,2026-02-24 10:36:22.667,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
3,58028,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Auto,Requerimientos,2026-02-25 12:16:58.070,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
4,61990,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Oficio,Oficio de citación,2026-03-13 16:45:53.050,13262002300,NIDIA CRUZ ORTEGA(Tequendama),NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
5,61992,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Oficio,Notificación personal medio electrónico,2026-03-13 11:20:32.767,13262002256,NIDIA CRUZ ORTEGA(Tequendama),NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
6,75313,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Resolución,Se hace un Requerimiento,2026-03-02 21:37:44.817,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
7,92374,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Auto,Requerimientos,2026-02-24 12:18:04.403,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
8,92787,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Acto Administrativo,Auto,Declara el Cumplimiento de Unas Obligaciones,2026-03-18 10:47:57.067,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
9,95731,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Acto Administrativo,Auto,Requerimientos,2026-03-17 12:03:21.453,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
10,97555,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Acto Administrativo,Auto,Requerimientos,2026-03-17 10:59:43.600,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
11,98118,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Auto,Requerimiento y realiza cobro por seguimiento ...,2026-02-22 20:27:08.340,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
12,99672,ALVARO ANDRES JIMENEZ VANEGAS,ALVARO ANDRES JIMENEZ VANEGAS,Seguimiento y Control,Seguimiento,Auto,Requerimiento y realiza cobro por seguimiento ...,2026-02-24 11:07:05.797,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
13,100797,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,Seguimiento y Control,Seguimiento,Auto,Cobro,2026-02-26 17:37:25.987,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
14,102015,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,Seguimiento y Control,Seguimiento,Auto,Exoneración de cobro de evaluación y/o seguimi...,2026-03-23 19:07:07.950,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
15,102449,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,Seguimiento y Control,Seguimiento,Auto,Cobro,2026-03-07 08:50:33.890,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
16,102478,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,Seguimiento y Control,Acto Administrativo,Auto,Requerimientos,2026-03-12 15:02:17.683,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
17,104105,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,Seguimiento y Control,Seguimiento,Auto,Cobro,2026-03-07 10:27:28.163,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
18,104329,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,Seguimiento y Control,Seguimiento,Auto,Cobro,2026-02-28 11:20:38.333,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO
19,110042,FRANCY LILIANA DAZA SANCHEZ,FRANCY LILIANA DAZA SANCHEZ,Seguimiento y Control,Seguimiento,Auto,Exoneración de cobro de evaluación y/o seguimi...,2026-03-23 08:11:45.747,nan,nan,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Firmado/Finalizado,FINALIZADO

,nombre_persona,estado_pelota_caliente,total_expedientes,total_registros
0,ALVARO ANDRES JIMENEZ VANEGAS,Firmado/Finalizado,13,13
1,FRANCY LILIANA DAZA SANCHEZ,Firmado/Finalizado,22,22
2,GINA ALEXANDRA ROBERTO TORRES,Firmado/Finalizado,21,21
3,ISABEL CRISTINA ANGARITA PERPINAN,Firmado/Finalizado,28,28
4,MARIA FERNANDA ARIAS OYUELA,Firmado/Finalizado,26,26

# exporte

In [6]:
ruta_salida = utils.exportar_reporte_seguimiento_sae_sidcar(
    df_final=df_seguimiento,
    carpeta_salida="output_SIDCAR",
    nombre_archivo="seguimiento_sae_sidcar.xlsx",
)

print("Archivo generado en:", ruta_salida)

✅ Reporte guardado en: output_SIDCAR\seguimiento_sae_sidcar.xlsx
Archivo generado en: output_SIDCAR\seguimiento_sae_sidcar.xlsx